tasks:
  - name: eslint
    init: npm install eslint --save-dev
  - name: servidor
    init: npm install 

ports:
  - port: 3000
    onOpen: open-browser

vscode:
  extensions:
    - dbaeumer.vscode-eslint